const state={category:'전체',query:'',openSource:false,free:false,favoritesOnly:false,platform:'all',sort:'popular'};
let tools=[];
const FAVORITES_KEY='openshelf-favorites-v1';
const favorites=new Set(JSON.parse(localStorage.getItem(FAVORITES_KEY)||'[]'));
const categoryDescriptions={'AI · 이미지':'이미지 생성·보정·업스케일','AI · LLM':'로컬 AI와 대화형 도구','AI · 에이전트':'에이전트 확장·전문 작업 스킬','AI · 애니메이션':'AI 코딩 기반 캐릭터·영상 제작','AI · 모델':'분류·판단·로컬 모델 도구','AI · CAD':'AI 기반 3D 설계·CAD 제작','디자인':'UI, 드로잉, 다이어그램','개발':'API, 데이터베이스, 개발 도구','생산성':'파일, 캡처, 업무 자동화','문서 · PDF':'PDF와 문서 처리','영상 · 미디어':'녹화, 방송, 변환'};
const collections=[
  {id:'quick-web',kicker:'NO INSTALL',title:'설치 없이 바로',description:'브라우저만 열면 바로 사용할 수 있는 웹 기반 도구.',filter:t=>t.platforms.includes('Web')},
  {id:'windows',kicker:'WINDOWS KIT',title:'윈도우 필수 도구',description:'Windows에서 바로 설치해 쓸 만한 생산성·미디어 도구.',filter:t=>t.platforms.includes('Windows')},
  {id:'selfhost',kicker:'SELF HOSTED',title:'내가 직접 운영하기',description:'외부 서비스에 맡기지 않고 직접 운영할 수 있는 도구.',filter:t=>(t.tags||[]).includes('셀프호스트')}
];

const els={
  search:document.querySelector('#search'),searchWrap:document.querySelector('#searchWrap'),categoryChips:document.querySelector('#categoryChips'),categoryGrid:document.querySelector('#categoryGrid'),
  collectionGrid:document.querySelector('#collectionGrid'),openSourceOnly:document.querySelector('#openSourceOnly'),freeOnly:document.querySelector('#freeOnly'),
  favoritesOnly:document.querySelector('#favoritesOnly'),platformFilter:document.querySelector('#platformFilter'),sortSelect:document.querySelector('#sortSelect'),
  toolGrid:document.querySelector('#toolGrid'),resultCount:document.querySelector('#resultCount'),emptyState:document.querySelector('#emptyState'),
  favoriteCount:document.querySelector('#favoriteCount'),favoritesNav:document.querySelector('#favoritesNav'),mobileFavorites:document.querySelector('#mobileFavorites'),
  mobileFavoriteCount:document.querySelector('#mobileFavoriteCount'),latestGrid:document.querySelector('#latestGrid'),heroToolCount:document.querySelector('#heroToolCount'),
  toolDialog:document.querySelector('#toolDialog'),dialogContent:document.querySelector('#dialogContent'),dialogClose:document.querySelector('#dialogClose'),
  resetFilters:document.querySelector('#resetFilters'),scrollToAll:document.querySelector('#scrollToAll'),statCategories:document.querySelector('#statCategories'),
  statPlatforms:document.querySelector('#statPlatforms'),statOpenSource:document.querySelector('#statOpenSource'),mobileMenuButton:document.querySelector('#mobileMenuButton'),
  mobileMenu:document.querySelector('#mobileMenu'),activeFilters:document.querySelector('#activeFilters'),resultContext:document.querySelector('#resultContext'),loadingState:document.querySelector('#loadingState'),errorState:document.querySelector('#errorState'),retryLoad:document.querySelector('#retryLoad')
};

function saveFavorites(){localStorage.setItem(FAVORITES_KEY,JSON.stringify([...favorites]));els.favoriteCount.textContent=favorites.size;els.mobileFavoriteCount.textContent=favorites.size}
function toolMatches(tool){const haystack=[tool.name,tool.description,tool.longDescription||'',tool.category,...(tool.tags||[]),...(tool.platforms||[])].join(' ').toLowerCase();return(!state.query||haystack.includes(state.query))&&(state.category==='전체'||tool.category===state.category)&&(!state.openSource||tool.openSource)&&(!state.free||tool.free)&&(!state.favoritesOnly||favorites.has(tool.id))&&(state.platform==='all'||tool.platforms.includes(state.platform))}
function renderChips(){const categories=['전체',...new Set(tools.map(t=>t.category))];els.categoryChips.innerHTML=categories.map(c=>`<button class="chip ${state.category===c?'active':''}" data-category="${c}">${c}</button>`).join('');els.categoryChips.querySelectorAll('.chip').forEach(btn=>btn.addEventListener('click',()=>applyCategory(btn.dataset.category)))}
function applyCategory(category){state.category=category;renderChips();renderTools();document.querySelector('#tools').scrollIntoView({behavior:'smooth'})}
function renderCategories(){const categories=[...new Set(tools.map(t=>t.category))];const remainder=categories.length%4;els.categoryGrid.dataset.remainder=String(remainder);els.categoryGrid.innerHTML=categories.map((c,i)=>{const count=tools.filter(t=>t.category===c).length;return `<article class="category-card" data-tone="${categoryTone(c)}" data-category-card="${c}" tabindex="0"><span class="index">${String(i+1).padStart(2,'0')}</span><div><h3>${c}</h3><p>${categoryDescriptions[c]||'분류된 도구 모음'}</p></div><footer><span>${count} tools</span><span>Explore</span></footer></article>`}).join('');els.categoryGrid.querySelectorAll('[data-category-card]').forEach(el=>{const go=()=>applyCategory(el.dataset.categoryCard);el.addEventListener('click',go);el.addEventListener('keydown',e=>{if(e.key==='Enter')go()})})}
function renderCollections(){els.collectionGrid.innerHTML=collections.map(c=>{const count=tools.filter(c.filter).length;return `<article class="collection-card" data-collection="${c.id}" tabindex="0"><span>${c.kicker}</span><h3>${c.title}</h3><p>${c.description}</p><button type="button">${count}개 보기 →</button></article>`}).join('');els.collectionGrid.querySelectorAll('[data-collection]').forEach(el=>{const go=()=>{const c=collections.find(x=>x.id===el.dataset.collection);resetFilters(false);if(c.id==='quick-web'){state.platform='Web';els.platformFilter.value='Web'}else if(c.id==='windows'){state.platform='Windows';els.platformFilter.value='Windows'}else if(c.id==='selfhost'){state.query='셀프호스트';els.search.value='셀프호스트'}renderTools();document.querySelector('#tools').scrollIntoView({behavior:'smooth'})};el.addEventListener('click',go);el.addEventListener('keydown',e=>{if(e.key==='Enter')go()})})}
function tagsFor(tool){return[...(tool.tags||[]),...(tool.free?['무료']:[]),...(tool.openSource?['오픈소스']:[])]}
function categoryTone(category){if(category.startsWith('AI'))return'ai';if(category==='디자인')return'design';if(category==='개발')return'dev';if(category==='생산성')return'productivity';if(category.includes('문서'))return'document';if(category.includes('영상'))return'media';return'default'}
function iconUrl(tool){if(tool.icon)return tool.icon;if(!tool.website)return'';try{const host=new URL(tool.website).hostname;return `https://www.google.com/s2/favicons?domain=${host}&sz=128`}catch{return''}}
function visualMarkup(tool,large=false){const url=iconUrl(tool);const cls=large?'dialog-logo tool-visual':'logo tool-visual';const letter=tool.name.slice(0,1).toUpperCase();return `<div class="${cls}">${url?`<img src="${url}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.hidden=true">`:''}<span class="fallback-letter">${letter}</span></div>`}
function compactNumber(n){if(!Number.isFinite(Number(n)))return'—';const v=Number(n);if(v>=1000000)return (v/1000000).toFixed(v>=10000000?0:1).replace(/\.0$/,'')+'m';if(v>=1000)return (v/1000).toFixed(v>=10000?0:1).replace(/\.0$/,'')+'k';return String(v)}
function popularityMeta(tool){return tool.github&&Number.isFinite(Number(tool.stars))?`<div class="popularity-meta" title="GitHub Stars / Forks"><span>★ ${compactNumber(tool.stars)}</span><span>⑂ ${compactNumber(tool.forks||0)}</span></div>`:''}
function card(tool){return `<article class="card" data-tone="${categoryTone(tool.category)}" data-id="${tool.id}"><div class="card-head">${visualMarkup(tool)}<div class="card-meta"><span class="category">${tool.category}</span><button class="favorite-btn ${favorites.has(tool.id)?'active':''}" data-favorite="${tool.id}" type="button" aria-label="즐겨찾기">${favorites.has(tool.id)?'♥':'♡'}</button></div></div><h2>${tool.name}</h2><p>${tool.description}</p><div class="tags">${tagsFor(tool).slice(0,5).map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="card-bottom-meta"><div class="platforms">${tool.platforms.join(' · ')}</div>${popularityMeta(tool)}</div><div class="card-actions">${tool.website?`<a class="primary" href="${tool.website}" target="_blank" rel="noreferrer">사용하기 ↗</a>`:''}<button type="button" data-detail="${tool.id}">자세히</button></div></article>`}
function syncUrl(detailId=null){const p=new URLSearchParams();if(state.query)p.set('q',state.query);if(state.category!=='전체')p.set('category',state.category);if(state.platform!=='all')p.set('platform',state.platform);if(state.openSource)p.set('open','1');if(state.free)p.set('free','1');if(state.favoritesOnly)p.set('favorites','1');if(state.sort!=='popular')p.set('sort',state.sort);if(detailId)p.set('tool',detailId);const next=location.pathname+(p.toString()?'?'+p.toString():'')+location.hash;history.replaceState(null,'',next)}
function restoreStateFromUrl(){const p=new URLSearchParams(location.search);state.query=(p.get('q')||'').toLowerCase();state.category=p.get('category')||'전체';state.platform=p.get('platform')||'all';state.openSource=p.get('open')==='1';state.free=p.get('free')==='1';state.favoritesOnly=p.get('favorites')==='1';state.sort=p.get('sort')||'popular';els.search.value=state.query;els.platformFilter.value=state.platform;els.openSourceOnly.checked=state.openSource;els.freeOnly.checked=state.free;els.favoritesOnly.checked=state.favoritesOnly;els.sortSelect.value=state.sort}
function renderTools(){let results=tools.filter(toolMatches);if(state.sort==='name')results.sort((a,b)=>a.name.localeCompare(b.name));else if(state.sort==='newest')results.sort((a,b)=>String(b.added||'').localeCompare(String(a.added||'')));else if(state.sort==='featured')results.sort((a,b)=>(b.featured||0)-(a.featured||0)||(b.stars||0)-(a.stars||0));else results.sort((a,b)=>(b.stars||0)-(a.stars||0)||(b.forks||0)-(a.forks||0)||(b.featured||0)-(a.featured||0));els.toolGrid.innerHTML=results.map(card).join('');els.resultCount.textContent=`${results.length} tools`;els.resultContext.textContent=resultContextText();els.emptyState.hidden=results.length!==0;renderActiveFilters();bindDynamicEvents();syncUrl()}
function renderLatest(){const latest=[...tools].sort((a,b)=>String(b.added||'').localeCompare(String(a.added||''))).slice(0,4);els.latestGrid.innerHTML=latest.map(tool=>`<article class="latest-card" data-tone="${categoryTone(tool.category)}" data-latest="${tool.id}" tabindex="0"><div class="latest-top">${visualMarkup(tool)}<span class="latest-badge">NEW</span></div><span class="latest-category">${tool.category}</span><h3>${tool.name}</h3><p>${tool.description}</p><time datetime="${tool.added||''}">${tool.added||''}</time></article>`).join('');els.latestGrid.querySelectorAll('[data-latest]').forEach(el=>{const open=()=>openDetail(el.dataset.latest);el.addEventListener('click',open);el.addEventListener('keydown',e=>{if(e.key==='Enter')open()})})}
function relatedTools(tool){return tools.filter(t=>t.id!==tool.id&&(t.category===tool.category||(t.tags||[]).some(tag=>(tool.tags||[]).includes(tag)))).sort((a,b)=>(b.featured||0)-(a.featured||0)).slice(0,4)}
function usageGuideMarkup(tool){if(!tool.install?.length&&!tool.usageSteps?.length&&!tool.requirements?.length&&!tool.examplePrompt)return'';const requirements=tool.requirements?.length?`<div class="usage-subsection"><h4>필요한 환경</h4><div class="requirement-list">${tool.requirements.map(x=>`<span>${x}</span>`).join('')}</div></div>`:'';const installs=tool.install?.length?`<div class="usage-subsection"><h4>설치</h4>${tool.install.map((x,i)=>`<div class="install-block"><div class="install-head"><strong>${x.title||'설치 명령어'}</strong><button type="button" data-copy-command="${i}">복사</button></div><code>${x.command}</code>${x.note?`<p>${x.note}</p>`:''}</div>`).join('')}</div>`:'';const steps=tool.usageSteps?.length?`<div class="usage-subsection"><h4>사용 순서</h4><ol class="usage-steps">${tool.usageSteps.map(x=>`<li>${x}</li>`).join('')}</ol></div>`:'';const prompt=tool.examplePrompt?`<div class="usage-subsection"><h4>예시 요청</h4><div class="prompt-example"><code>${tool.examplePrompt}</code><button type="button" data-copy-prompt>복사</button></div></div>`:'';const agents=tool.supportedAgents?.length?`<div class="usage-subsection"><h4>지원 에이전트</h4><div class="requirement-list">${tool.supportedAgents.map(x=>`<span>${x}</span>`).join('')}</div></div>`:'';return `<div class="usage-guide"><div class="usage-guide-title"><span>HOW TO USE</span><h3>사용 방법</h3></div>${tool.usageNote?`<p class="usage-note">${tool.usageNote}</p>`:''}${requirements}${installs}${steps}${prompt}${agents}</div>`}
function bindUsageCopy(tool){els.dialogContent.querySelectorAll('[data-copy-command]').forEach(btn=>btn.addEventListener('click',async()=>{const item=tool.install?.[Number(btn.dataset.copyCommand)];if(!item)return;try{await navigator.clipboard.writeText(item.command);const old=btn.textContent;btn.textContent='복사됨';setTimeout(()=>btn.textContent=old,1200)}catch{}}));const promptBtn=els.dialogContent.querySelector('[data-copy-prompt]');if(promptBtn&&tool.examplePrompt)promptBtn.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(tool.examplePrompt);const old=promptBtn.textContent;promptBtn.textContent='복사됨';setTimeout(()=>promptBtn.textContent=old,1200)}catch{}})}
function openDetail(id){const tool=tools.find(t=>t.id===id);if(!tool)return;const related=relatedTools(tool);const isFav=favorites.has(tool.id);els.dialogContent.innerHTML=`<div class="dialog-body" style="--tool-tint:var(--soft)"><div class="dialog-hero">${visualMarkup(tool,true)}<div><span class="dialog-kicker">${tool.category}</span><div class="dialog-title-row"><h2>${tool.name}</h2><button class="dialog-favorite ${isFav?'active':''}" type="button" data-dialog-favorite="${tool.id}">${isFav?'♥ 저장됨':'♡ 즐겨찾기'}</button></div><p>${tool.longDescription||tool.description}</p></div></div><div class="tags">${tagsFor(tool).map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="detail-meta"><div class="detail-box"><span>PLATFORMS</span><strong>${tool.platforms.join(', ')}</strong></div><div class="detail-box"><span>LICENSE</span><strong>${tool.license||'확인 필요'}</strong></div><div class="detail-box"><span>PRICE</span><strong>${tool.free?'무료':'유/무료 혼합'}</strong></div><div class="detail-box"><span>ADDED</span><strong>${tool.added||'—'}</strong></div>${tool.github&&Number.isFinite(Number(tool.stars))?`<div class="detail-box"><span>GITHUB STARS</span><strong>★ ${Number(tool.stars).toLocaleString()}</strong></div><div class="detail-box"><span>FORKS</span><strong>${Number(tool.forks||0).toLocaleString()}</strong></div>`:''}</div><div class="detail-section"><h3>이런 때 유용해요</h3><p>${tool.description}</p></div>${usageGuideMarkup(tool)}${related.length?`<div class="related"><h3>비슷한 도구</h3><div class="related-list">${related.map(r=>`<button type="button" data-related="${r.id}">${r.name}</button>`).join('')}</div></div>`:''}<div class="dialog-actions">${tool.website?`<a class="primary" href="${tool.website}" target="_blank" rel="noreferrer">공식 사이트 ↗</a>`:''}${tool.github?`<a href="${tool.github}" target="_blank" rel="noreferrer">GitHub ↗</a>`:''}</div></div>`;els.dialogContent.querySelectorAll('[data-related]').forEach(btn=>btn.addEventListener('click',()=>openDetail(btn.dataset.related)));const favBtn=els.dialogContent.querySelector('[data-dialog-favorite]');if(favBtn)favBtn.addEventListener('click',()=>{toggleFavorite(tool.id);openDetail(tool.id)});bindUsageCopy(tool);els.toolDialog.showModal();document.body.classList.add('dialog-open');syncUrl(tool.id)}
function closeDialog(){els.toolDialog.close();document.body.classList.remove('dialog-open');syncUrl()}
function toggleFavorite(id){favorites.has(id)?favorites.delete(id):favorites.add(id);saveFavorites();renderTools()}
function bindDynamicEvents(){els.toolGrid.querySelectorAll('[data-favorite]').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();toggleFavorite(btn.dataset.favorite)}));els.toolGrid.querySelectorAll('[data-detail]').forEach(btn=>btn.addEventListener('click',()=>openDetail(btn.dataset.detail)))}
function resetFilters(scroll=true){Object.assign(state,{category:'전체',query:'',openSource:false,free:false,favoritesOnly:false,platform:'all',sort:'popular'});els.search.value='';els.openSourceOnly.checked=false;els.freeOnly.checked=false;els.favoritesOnly.checked=false;els.platformFilter.value='all';els.sortSelect.value='popular';renderChips();renderTools();if(scroll)document.querySelector('#tools').scrollIntoView({behavior:'smooth'})}
function renderStats(){els.statCategories.textContent=new Set(tools.map(t=>t.category)).size;els.statPlatforms.textContent=new Set(tools.flatMap(t=>t.platforms)).size;els.statOpenSource.textContent=tools.filter(t=>t.openSource).length}
function resultContextText(){const parts=[];if(state.query)parts.push(`“${state.query}” 검색`);if(state.category!=='전체')parts.push(state.category);if(state.platform!=='all')parts.push(state.platform);if(state.openSource)parts.push('오픈소스');if(state.free)parts.push('무료');if(state.favoritesOnly)parts.push('즐겨찾기');return parts.length?' · '+parts.join(' · '):' · 전체 도구'}
function activeFilterItems(){const items=[];if(state.query)items.push({key:'query',label:`검색: ${state.query}`});if(state.category!=='전체')items.push({key:'category',label:state.category});if(state.platform!=='all')items.push({key:'platform',label:state.platform});if(state.openSource)items.push({key:'openSource',label:'오픈소스'});if(state.free)items.push({key:'free',label:'무료'});if(state.favoritesOnly)items.push({key:'favoritesOnly',label:'즐겨찾기'});return items}
function clearOneFilter(key){if(key==='query'){state.query='';els.search.value=''}else if(key==='category'){state.category='전체';renderChips()}else if(key==='platform'){state.platform='all';els.platformFilter.value='all'}else if(key==='openSource'){state.openSource=false;els.openSourceOnly.checked=false}else if(key==='free'){state.free=false;els.freeOnly.checked=false}else if(key==='favoritesOnly'){state.favoritesOnly=false;els.favoritesOnly.checked=false}renderTools()}
function renderActiveFilters(){const items=activeFilterItems();els.activeFilters.hidden=items.length===0;if(!items.length){els.activeFilters.innerHTML='';return}els.activeFilters.innerHTML=items.map(x=>`<span class="active-filter">${x.label}<button type="button" data-clear-filter="${x.key}" aria-label="${x.label} 제거">×</button></span>`).join('')+`<button type="button" class="active-filter clear-all" data-clear-all>전체 해제</button>`;els.activeFilters.querySelectorAll('[data-clear-filter]').forEach(btn=>btn.addEventListener('click',()=>clearOneFilter(btn.dataset.clearFilter)));els.activeFilters.querySelector('[data-clear-all]').addEventListener('click',()=>resetFilters(false))}
function openFavorites(){state.favoritesOnly=true;els.favoritesOnly.checked=true;closeMobileMenu();document.querySelector('#tools').scrollIntoView({behavior:'smooth'});renderTools()}
function toggleMobileMenu(){const open=!els.mobileMenu.classList.contains('open');els.mobileMenu.classList.toggle('open',open);els.mobileMenuButton.classList.toggle('active',open);els.mobileMenuButton.setAttribute('aria-expanded',String(open));els.mobileMenu.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('menu-open',open)}
function closeMobileMenu(){els.mobileMenu.classList.remove('open');els.mobileMenuButton.classList.remove('active');els.mobileMenuButton.setAttribute('aria-expanded','false');els.mobileMenu.setAttribute('aria-hidden','true');document.body.classList.remove('menu-open')}
function setupReveal(){const items=document.querySelectorAll('.reveal');if(!('IntersectionObserver'in window)){items.forEach(x=>x.classList.add('visible'));return}const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});items.forEach(x=>io.observe(x))}
function setupActiveNav(){const navLinks=[...document.querySelectorAll('[data-nav]')];const sections=navLinks.map(a=>document.querySelector('#'+a.dataset.nav)).filter(Boolean);const update=()=>{const probe=window.scrollY+120;let active='';for(const section of sections){if(probe>=section.offsetTop)active=section.id}navLinks.forEach(a=>a.classList.toggle('active',!!active&&a.dataset.nav===active));document.querySelector('.topbar')?.classList.toggle('compact',window.scrollY>120)};window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);update()}
els.search.addEventListener('input',e=>{state.query=e.target.value.trim().toLowerCase();renderTools()});els.search.addEventListener('focus',()=>els.searchWrap.classList.add('focused'));els.search.addEventListener('blur',()=>els.searchWrap.classList.remove('focused'));
els.openSourceOnly.addEventListener('change',e=>{state.openSource=e.target.checked;renderTools()});els.freeOnly.addEventListener('change',e=>{state.free=e.target.checked;renderTools()});els.favoritesOnly.addEventListener('change',e=>{state.favoritesOnly=e.target.checked;renderTools()});els.platformFilter.addEventListener('change',e=>{state.platform=e.target.value;renderTools()});els.sortSelect.addEventListener('change',e=>{state.sort=e.target.value;renderTools()});
els.favoritesNav.addEventListener('click',openFavorites);els.mobileFavorites.addEventListener('click',openFavorites);els.scrollToAll.addEventListener('click',()=>document.querySelector('#tools').scrollIntoView({behavior:'smooth'}));els.resetFilters.addEventListener('click',()=>resetFilters());els.dialogClose.addEventListener('click',closeDialog);els.toolDialog.addEventListener('click',e=>{if(e.target===els.toolDialog)closeDialog()});els.mobileMenuButton.addEventListener('click',toggleMobileMenu);els.mobileMenu.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',closeMobileMenu));
document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==els.search){e.preventDefault();els.search.focus()}if(e.key==='Escape'&&els.toolDialog.open)closeDialog();else if(e.key==='Escape')closeMobileMenu()});
async function loadTools(){els.loadingState.hidden=false;els.errorState.hidden=true;els.toolGrid.hidden=true;try{const r=await fetch('./data/tools.json',{cache:'no-store'});if(!r.ok)throw new Error('load failed');tools=await r.json();restoreStateFromUrl();els.heroToolCount.textContent=tools.length;saveFavorites();renderChips();renderCategories();renderCollections();renderLatest();renderStats();renderTools();els.loadingState.hidden=true;els.toolGrid.hidden=false;setupReveal();setupActiveNav();const detailId=new URLSearchParams(location.search).get('tool');if(detailId&&tools.some(t=>t.id===detailId))openDetail(detailId)}catch{els.loadingState.hidden=true;els.errorState.hidden=false;els.toolGrid.hidden=true}}
els.retryLoad.addEventListener('click',loadTools);
window.addEventListener('popstate',()=>{if(!tools.length)return;restoreStateFromUrl();renderChips();renderTools();const detailId=new URLSearchParams(location.search).get('tool');if(detailId)openDetail(detailId);else if(els.toolDialog.open)closeDialog()});
loadTools();
