const state={category:'전체',query:'',openSource:false,free:false,favoritesOnly:false,platform:'all',sort:'featured'};
let tools=[];
const FAVORITES_KEY='openshelf-favorites-v1';
const favorites=new Set(JSON.parse(localStorage.getItem(FAVORITES_KEY)||'[]'));
const categoryDescriptions={'AI · 이미지':'이미지 생성·보정·업스케일','AI · LLM':'로컬 AI와 대화형 도구','디자인':'UI, 드로잉, 다이어그램','개발':'API, 데이터베이스, 개발 도구','생산성':'파일, 캡처, 업무 자동화','문서 · PDF':'PDF와 문서 처리','영상 · 미디어':'녹화, 방송, 변환'};
const collections=[
  {id:'quick-web',kicker:'NO INSTALL',title:'설치 없이 바로',description:'브라우저만 열면 바로 사용할 수 있는 웹 기반 도구.',filter:t=>t.platforms.includes('Web')},
  {id:'windows',kicker:'WINDOWS KIT',title:'윈도우 필수 도구',description:'Windows에서 바로 설치해 쓸 만한 생산성·미디어 도구.',filter:t=>t.platforms.includes('Windows')},
  {id:'selfhost',kicker:'SELF HOSTED',title:'내가 직접 운영하기',description:'외부 서비스에 맡기지 않고 직접 운영할 수 있는 도구.',filter:t=>(t.tags||[]).includes('셀프호스트')}
];

const els={
  search:document.querySelector('#search'),searchWrap:document.querySelector('#searchWrap'),categoryChips:document.querySelector('#categoryChips'),categoryGrid:document.querySelector('#categoryGrid'),
  collectionGrid:document.querySelector('#collectionGrid'),openSourceOnly:document.querySelector('#openSourceOnly'),freeOnly:document.querySelector('#freeOnly'),
  favoritesOnly:document.querySelector('#favoritesOnly'),platformFilter:document.querySelector('#platformFilter'),sortSelect:document.querySelector('#sortSelect'),
  toolGrid:document.querySelector('#toolGrid'),resultCount:document.querySelector('#resultCount'),emptyState:document.querySelector('#emptyState'),
  favoriteCount:document.querySelector('#favoriteCount'),favoritesNav:document.querySelector('#favoritesNav'),mobileFavorites:document.querySelector('#mobileFavorites'),
  mobileFavoriteCount:document.querySelector('#mobileFavoriteCount'),latestGrid:document.querySelector('#latestGrid'),heroToolCount:document.querySelector('#heroToolCount'),
  toolDialog:document.querySelector('#toolDialog'),dialogContent:document.querySelector('#dialogContent'),dialogClose:document.querySelector('#dialogClose'),
  resetFilters:document.querySelector('#resetFilters'),scrollToAll:document.querySelector('#scrollToAll'),statCategories:document.querySelector('#statCategories'),
  statPlatforms:document.querySelector('#statPlatforms'),statOpenSource:document.querySelector('#statOpenSource'),mobileMenuButton:document.querySelector('#mobileMenuButton'),
  mobileMenu:document.querySelector('#mobileMenu')
};

function saveFavorites(){localStorage.setItem(FAVORITES_KEY,JSON.stringify([...favorites]));els.favoriteCount.textContent=favorites.size;els.mobileFavoriteCount.textContent=favorites.size}
function toolMatches(tool){const haystack=[tool.name,tool.description,tool.longDescription||'',tool.category,...(tool.tags||[]),...(tool.platforms||[])].join(' ').toLowerCase();return(!state.query||haystack.includes(state.query))&&(state.category==='전체'||tool.category===state.category)&&(!state.openSource||tool.openSource)&&(!state.free||tool.free)&&(!state.favoritesOnly||favorites.has(tool.id))&&(state.platform==='all'||tool.platforms.includes(state.platform))}
function renderChips(){const categories=['전체',...new Set(tools.map(t=>t.category))];els.categoryChips.innerHTML=categories.map(c=>`<button class="chip ${state.category===c?'active':''}" data-category="${c}">${c}</button>`).join('');els.categoryChips.querySelectorAll('.chip').forEach(btn=>btn.addEventListener('click',()=>applyCategory(btn.dataset.category)))}
function applyCategory(category){state.category=category;renderChips();renderTools();document.querySelector('#tools').scrollIntoView({behavior:'smooth'})}
function renderCategories(){const categories=[...new Set(tools.map(t=>t.category))];els.categoryGrid.innerHTML=categories.map((c,i)=>{const count=tools.filter(t=>t.category===c).length;return `<article class="category-card" data-category-card="${c}" tabindex="0"><span class="index">${String(i+1).padStart(2,'0')}</span><div><h3>${c}</h3><p>${categoryDescriptions[c]||'분류된 도구 모음'}</p></div><footer><span>${count} tools</span><span>Explore</span></footer></article>`}).join('');els.categoryGrid.querySelectorAll('[data-category-card]').forEach(el=>{const go=()=>applyCategory(el.dataset.categoryCard);el.addEventListener('click',go);el.addEventListener('keydown',e=>{if(e.key==='Enter')go()})})}
function renderCollections(){els.collectionGrid.innerHTML=collections.map(c=>{const count=tools.filter(c.filter).length;return `<article class="collection-card" data-collection="${c.id}" tabindex="0"><span>${c.kicker}</span><h3>${c.title}</h3><p>${c.description}</p><button type="button">${count}개 보기 →</button></article>`}).join('');els.collectionGrid.querySelectorAll('[data-collection]').forEach(el=>{const go=()=>{const c=collections.find(x=>x.id===el.dataset.collection);resetFilters(false);if(c.id==='quick-web'){state.platform='Web';els.platformFilter.value='Web'}else if(c.id==='windows'){state.platform='Windows';els.platformFilter.value='Windows'}else if(c.id==='selfhost'){state.query='셀프호스트';els.search.value='셀프호스트'}renderTools();document.querySelector('#tools').scrollIntoView({behavior:'smooth'})};el.addEventListener('click',go);el.addEventListener('keydown',e=>{if(e.key==='Enter')go()})})}
function tagsFor(tool){return[...(tool.tags||[]),...(tool.free?['무료']:[]),...(tool.openSource?['오픈소스']:[])]}
function card(tool){const letter=tool.name.slice(0,1).toUpperCase();return `<article class="card" data-id="${tool.id}"><div class="card-head"><div class="logo">${letter}</div><div class="card-meta"><span class="category">${tool.category}</span><button class="favorite-btn ${favorites.has(tool.id)?'active':''}" data-favorite="${tool.id}" type="button" aria-label="즐겨찾기">${favorites.has(tool.id)?'♥':'♡'}</button></div></div><h2>${tool.name}</h2><p>${tool.description}</p><div class="tags">${tagsFor(tool).slice(0,5).map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="platforms">${tool.platforms.join(' · ')}</div><div class="card-actions">${tool.website?`<a class="primary" href="${tool.website}" target="_blank" rel="noreferrer">사용하기 ↗</a>`:''}<button type="button" data-detail="${tool.id}">자세히</button></div></article>`}
function renderTools(){let results=tools.filter(toolMatches);if(state.sort==='name')results.sort((a,b)=>a.name.localeCompare(b.name));else if(state.sort==='newest')results.sort((a,b)=>String(b.added||'').localeCompare(String(a.added||'')));else results.sort((a,b)=>(b.featured||0)-(a.featured||0));els.toolGrid.innerHTML=results.map(card).join('');els.resultCount.textContent=`${results.length} tools`;els.emptyState.hidden=results.length!==0;bindDynamicEvents()}
function renderLatest(){const latest=[...tools].sort((a,b)=>String(b.added||'').localeCompare(String(a.added||''))).slice(0,4);els.latestGrid.innerHTML=latest.map(tool=>`<article class="latest-card" data-latest="${tool.id}" tabindex="0"><span>${tool.category}</span><h3>${tool.name}</h3><p>${tool.description}</p></article>`).join('');els.latestGrid.querySelectorAll('[data-latest]').forEach(el=>{const open=()=>openDetail(el.dataset.latest);el.addEventListener('click',open);el.addEventListener('keydown',e=>{if(e.key==='Enter')open()})})}
function relatedTools(tool){return tools.filter(t=>t.id!==tool.id&&(t.category===tool.category||(t.tags||[]).some(tag=>(tool.tags||[]).includes(tag)))).sort((a,b)=>(b.featured||0)-(a.featured||0)).slice(0,4)}
function openDetail(id){const tool=tools.find(t=>t.id===id);if(!tool)return;const related=relatedTools(tool);els.dialogContent.innerHTML=`<div class="dialog-body"><span class="dialog-kicker">${tool.category}</span><h2>${tool.name}</h2><p>${tool.longDescription||tool.description}</p><div class="tags">${tagsFor(tool).map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="detail-grid"><div class="detail-box"><span>PLATFORMS</span><strong>${tool.platforms.join(', ')}</strong></div><div class="detail-box"><span>LICENSE</span><strong>${tool.license||'확인 필요'}</strong></div><div class="detail-box"><span>PRICE</span><strong>${tool.free?'무료':'유/무료 혼합'}</strong></div></div>${related.length?`<div class="related"><h3>비슷한 도구</h3><div class="related-list">${related.map(r=>`<button type="button" data-related="${r.id}">${r.name}</button>`).join('')}</div></div>`:''}<div class="dialog-actions">${tool.website?`<a class="primary" href="${tool.website}" target="_blank" rel="noreferrer">공식 사이트 ↗</a>`:''}${tool.github?`<a href="${tool.github}" target="_blank" rel="noreferrer">GitHub ↗</a>`:''}</div></div>`;els.dialogContent.querySelectorAll('[data-related]').forEach(btn=>btn.addEventListener('click',()=>openDetail(btn.dataset.related)));els.toolDialog.showModal();document.body.classList.add('dialog-open')}
function closeDialog(){els.toolDialog.close();document.body.classList.remove('dialog-open')}
function toggleFavorite(id){favorites.has(id)?favorites.delete(id):favorites.add(id);saveFavorites();renderTools()}
function bindDynamicEvents(){els.toolGrid.querySelectorAll('[data-favorite]').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();toggleFavorite(btn.dataset.favorite)}));els.toolGrid.querySelectorAll('[data-detail]').forEach(btn=>btn.addEventListener('click',()=>openDetail(btn.dataset.detail)))}
function resetFilters(scroll=true){Object.assign(state,{category:'전체',query:'',openSource:false,free:false,favoritesOnly:false,platform:'all',sort:'featured'});els.search.value='';els.openSourceOnly.checked=false;els.freeOnly.checked=false;els.favoritesOnly.checked=false;els.platformFilter.value='all';els.sortSelect.value='featured';renderChips();renderTools();if(scroll)document.querySelector('#tools').scrollIntoView({behavior:'smooth'})}
function renderStats(){els.statCategories.textContent=new Set(tools.map(t=>t.category)).size;els.statPlatforms.textContent=new Set(tools.flatMap(t=>t.platforms)).size;els.statOpenSource.textContent=tools.filter(t=>t.openSource).length}
function openFavorites(){state.favoritesOnly=true;els.favoritesOnly.checked=true;closeMobileMenu();document.querySelector('#tools').scrollIntoView({behavior:'smooth'});renderTools()}
function toggleMobileMenu(){const open=!els.mobileMenu.classList.contains('open');els.mobileMenu.classList.toggle('open',open);els.mobileMenuButton.classList.toggle('active',open);els.mobileMenuButton.setAttribute('aria-expanded',String(open));els.mobileMenu.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('menu-open',open)}
function closeMobileMenu(){els.mobileMenu.classList.remove('open');els.mobileMenuButton.classList.remove('active');els.mobileMenuButton.setAttribute('aria-expanded','false');els.mobileMenu.setAttribute('aria-hidden','true');document.body.classList.remove('menu-open')}
function setupReveal(){const items=document.querySelectorAll('.reveal');if(!('IntersectionObserver'in window)){items.forEach(x=>x.classList.add('visible'));return}const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});items.forEach(x=>io.observe(x))}
function setupActiveNav(){const navLinks=[...document.querySelectorAll('[data-nav]')];const sections=navLinks.map(a=>document.querySelector('#'+a.dataset.nav)).filter(Boolean);if(!('IntersectionObserver'in window))return;const io=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){navLinks.forEach(a=>a.classList.toggle('active',a.dataset.nav===entry.target.id))}})},{rootMargin:'-30% 0px -60% 0px'});sections.forEach(s=>io.observe(s))}
els.search.addEventListener('input',e=>{state.query=e.target.value.trim().toLowerCase();renderTools()});els.search.addEventListener('focus',()=>els.searchWrap.classList.add('focused'));els.search.addEventListener('blur',()=>els.searchWrap.classList.remove('focused'));
els.openSourceOnly.addEventListener('change',e=>{state.openSource=e.target.checked;renderTools()});els.freeOnly.addEventListener('change',e=>{state.free=e.target.checked;renderTools()});els.favoritesOnly.addEventListener('change',e=>{state.favoritesOnly=e.target.checked;renderTools()});els.platformFilter.addEventListener('change',e=>{state.platform=e.target.value;renderTools()});els.sortSelect.addEventListener('change',e=>{state.sort=e.target.value;renderTools()});
els.favoritesNav.addEventListener('click',openFavorites);els.mobileFavorites.addEventListener('click',openFavorites);els.scrollToAll.addEventListener('click',()=>document.querySelector('#tools').scrollIntoView({behavior:'smooth'}));els.resetFilters.addEventListener('click',()=>resetFilters());els.dialogClose.addEventListener('click',closeDialog);els.toolDialog.addEventListener('click',e=>{if(e.target===els.toolDialog)closeDialog()});els.mobileMenuButton.addEventListener('click',toggleMobileMenu);els.mobileMenu.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',closeMobileMenu));
document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==els.search){e.preventDefault();els.search.focus()}if(e.key==='Escape'&&els.toolDialog.open)closeDialog();else if(e.key==='Escape')closeMobileMenu()});
fetch('./data/tools.json').then(r=>r.json()).then(data=>{tools=data;els.heroToolCount.textContent=tools.length;saveFavorites();renderChips();renderCategories();renderCollections();renderLatest();renderStats();renderTools();setupReveal();setupActiveNav()}).catch(()=>{els.toolGrid.innerHTML='<p>도구 데이터를 불러오지 못했습니다.</p>'});
