// Catalog-backed trial navigator. Never executes untrusted repository code.
const search=document.getElementById('trialSearch'),filter=document.getElementById('trialFilter'),list=document.getElementById('trialList'),count=document.getElementById('trialCount'),more=document.getElementById('trialMore'),panel=document.getElementById('trialPanel');
let catalog=[],results=[],shown=0;
function safeLink(raw){try{const u=new URL(raw);return u.protocol==='https:'||u.protocol==='http:'?u.href:null}catch{return null}}
function modeOf(t){if(playgroundLink(t))return 'verified';if(safeLink(t.website)&&t.website!==t.github)return 'website';return 'guide'}
function lookup(){const q=search.value.trim().toLocaleLowerCase(),kind=filter.value;results=catalog.filter(t=>(kind==='all'||modeOf(t)===kind)&&(q===''||[t.name,t.description,t.category,...(t.tags||[])].join(' ').toLocaleLowerCase().includes(q)));shown=0;list.replaceChildren();renderMore()}
function renderMore(){const end=Math.min(shown+24,results.length);for(let i=shown;i<end;i++){const t=results[i],mode=modeOf(t);const card=document.createElement('article');card.className='hub-card';const top=document.createElement('div');top.className='hub-card-top';top.textContent=mode==='verified'?'체험 연결 확인':mode==='website'?'공식 웹사이트 제공 (실행 미확인)':'설치·사용 안내';const title=document.createElement('h2');title.textContent=t.name;const desc=document.createElement('p');desc.textContent=t.description||'설명 없음';const action=document.createElement('button');action.type='button';action.className='trial-open';action.textContent='체험 방법 보기 →';action.addEventListener('click',()=>openTrial(t));card.append(top,title,desc,action);list.append(card)}shown=end;more.hidden=shown>=results.length;count.textContent='전체 '+catalog.length+'개 중 '+results.length+'개 검색됨 · '+shown+'개 표시'}
function addLink(holder,label,raw){const href=safeLink(raw);if(!href)return;const a=document.createElement('a');a.href=href;a.target='_blank';a.rel='noopener noreferrer';a.textContent=label;holder.append(a)}
function openTrial(t){panel.hidden=false;document.getElementById('trialTitle').textContent=t.name;const note=document.getElementById('trialNotice'),steps=document.getElementById('trialSteps'),actions=document.getElementById('trialActions');steps.replaceChildren();actions.replaceChildren();const playground=playgroundLink(t);
note.textContent=playground?'사전 확인된 관련 체험 연결입니다. 원본 도구를 실행하는 것은 아닐 수 있습니다.':modeOf(t)==='website'?'공식 홈페이지는 등록되어 있지만 브라우저에서 직접 실행할 수 있는지는 확인되지 않았습니다.':'이 도구는 브라우저 내 실행이 검증되지 않았습니다. 설치 및 사용 절차를 확인하세요.';
if(Array.isArray(t.install)&&t.install.length){const title=document.createElement('h3');title.textContent='설치 정보';steps.append(title);for(const command of t.install.slice(0,4)){if(!command||typeof command.command!=='string')continue;const pre=document.createElement('pre');pre.textContent=command.command;steps.append(pre)}}
if(Array.isArray(t.usageSteps)&&t.usageSteps.length){const title=document.createElement('h3');title.textContent='실행 안내';const ol=document.createElement('ol');for(const value of t.usageSteps.slice(0,8)){const li=document.createElement('li');li.textContent=String(value);ol.append(li)}steps.append(title,ol)}
if(!steps.childElementCount){const p=document.createElement('p');p.textContent='상세 사용 절차가 등록되지 않았습니다. 공식 문서를 확인하세요.';steps.append(p)}
if(playground){const a=document.createElement('a');a.href=playground;a.textContent=playgroundIsOfficial(t)?'공식 웹 앱 체험 열기 ↗':'관련 기능 체험 열기 ↗';actions.append(a)}
addLink(actions,'공식 홈페이지 ↗',t.website);addLink(actions,'GitHub ↗',t.github);
panel.scrollIntoView({behavior:'smooth',block:'start'})}
search.addEventListener('input',lookup);filter.addEventListener('change',lookup);more.addEventListener('click',renderMore);document.getElementById('trialClose').addEventListener('click',()=>{panel.hidden=true});
fetch('data/tools.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json()}).then(data=>{if(!Array.isArray(data))throw Error('Invalid tools data');catalog=data.filter(t=>t&&typeof t.name==='string'&&typeof t.id==='string');lookup()}).catch(()=>{count.textContent='도구 목록을 불러오지 못했습니다. 새로고침해 주세요.'});
