import assert from 'node:assert/strict';
import {discoverIds,parseOfficialDetail,discover,searchUrl} from './discover-public-apis.mjs';
assert.ok(searchUrl(2).includes('dType=API'));
assert.deepEqual(discoverIds('<a href="/data/15129415/openapi.do">A</a><a href="/data/15129415/openapi.do">B</a>'),['15129415']);
assert.deepEqual(discoverIds('<a href="/data/15129415/fileData.do">file</a>'),[]);
const doc='<html><body>'+'.'.repeat(220)+' OpenAPI 명 조달청_나라장터 가격정보현황서비스 분류체계 일반공공행정 - 정부자원관리 제공기관 조달청 관리부서명 조달데이터관리팀 설명 시설자재가격 조회 서비스입니다. 건축, 토목 등 다양한 시장 가격을 제공합니다. API 유형 REST 데이터 포맷 JSON+XML 운영단계 : 자동승인 </body></html>';
const row=parseOfficialDetail(doc,'15129415');assert.equal(row?.provider,'조달청');assert.equal(row?.name,'조달청_나라장터 가격정보현황서비스');
assert.equal(parseOfficialDetail('<html>error</html>','15129415'),null);
let writes=[];
const current={'data/public-api-candidates.json':JSON.stringify({items:[]}), 'data/public-apis.json':JSON.stringify({items:[]}), 'data/public-api-discovery-state.json':JSON.stringify({nextPage:1})};
const fetcher=async url=>({ok:true,headers:new Headers({'content-type':'text/html'}),text:async()=>url.includes('selectDataSetList')?'<a href="/data/15129415/openapi.do">sample</a>':doc});
const result=await discover({pages:1,fetcher,read:async key=>current[key],write:async(key,val)=>writes.push({key,val})});
assert.equal(result.addedCandidates,1);assert.equal(writes.length,2);
assert.equal(JSON.parse(writes[0].val).items[0].id,'15129415');
writes=[];
const fail=await discover({pages:1,fetcher:async()=>{throw Error('offline')},read:async key=>current[key],write:async(key,val)=>writes.push({key,val})});
assert.equal(fail.addedCandidates,0);assert.equal(writes.length,0);
console.log('Official API discovery safe-mode tests passed');

writes=[];const resumed={...current,'data/public-api-discovery-state.json':JSON.stringify({nextPage:7})};
const more=await discover({pages:2,fetcher,read:async k=>resumed[k],write:async(k,v)=>writes.push({key:k,val:v})});
assert.equal(more.startPage,7);assert.equal(more.nextPage,9);assert.equal(more.scannedPages,2);
assert.equal(JSON.parse(writes.find(w=>w.key==='data/public-api-discovery-state.json').val).nextPage,9);
writes=[];const blocked=await discover({pages:2,fetcher:async u=>u.includes('selectDataSetList')?fetcher(u):Promise.reject(Error('offline detail')),read:async k=>current[k],write:async(k,v)=>writes.push({key:k,val:v})});
assert.equal(blocked.nextPage,3);assert.equal(blocked.detailErrors,2);
assert.deepEqual(JSON.parse(writes[0].val).failedDetails,['15129415']);
console.log('Resume cursor and fail-closed detail tests passed');
