import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {execFileSync} from 'node:child_process';
const js=fs.readFileSync('public-data.js','utf8');
const html=fs.readFileSync('public-data.html','utf8');
execFileSync(process.execPath,['--check','public-data.js']);
for(const id of ['fileSearch','fileSector','fileCategory','fileProvider','fileFormat'])assert.ok(html.includes('id="'+id+'"'),id);
const start=js.indexOf('const SECTORS='),end=js.indexOf('function valid(');
const context={};vm.runInNewContext(js.slice(start,end)+';globalThis.sectorOf=sectorOf;globalThis.formatsOf=formatsOf',context);
assert.equal(context.sectorOf('교통물류 - 도로'),'교통·물류');
assert.equal(context.sectorOf('보건 - 의료'),'보건·의료');
assert.equal(context.sectorOf('아무런 분류 없음'),'기타·미분류');
assert.equal(context.formatsOf('CSV, JSON').includes('CSV'),true);
assert.equal(context.formatsOf('CSV, JSON').includes('XML'),false);
assert.equal(context.formatsOf('XLSX').includes('XLS'),false);
assert.match(js,/formatsOf\(x.format\).includes\(format.value\)/);
assert.match(js,/sector.value!==sectorOf\(x.category\)/);
console.log('V23 Public Data sector and file format filtering tests passed');
