import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {execFileSync} from 'node:child_process';
const script=fs.readFileSync('public-api.js','utf8');
const html=fs.readFileSync('public-api.html','utf8');
execFileSync(process.execPath,['--check','public-api.js']);
for(const id of ['apiSector','apiVerification','apiCategory','apiProvider','apiFormat'])assert.ok(html.includes('id="'+id+'"'));
const source=script.slice(script.indexOf('const SECTOR_RULES='),script.indexOf('const indexedText='));
const api={};vm.runInNewContext(source+';globalThis.exports={sectorOf};',api);
const {sectorOf}=api.exports;
assert.equal(sectorOf('교통물류 - 도로'),'교통·물류');
assert.equal(sectorOf('환경 - 수질'),'환경·에너지');
assert.equal(sectorOf('보건 - 의료'),'보건·의료');
assert.equal(sectorOf('건축 - 도시'),'건축·시설');
assert.equal(sectorOf('알 수 없는 분류'),'기타·미분류');
assert.match(script,/verification==='verified'/);
assert.match(script,/verifiedIds/);
assert.match(script,/sectorCounts/);
console.log('V18 API sector classification and verification filter checks passed');
