import assert from 'node:assert/strict';
import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
const js=fs.readFileSync('public-api.js','utf8');
const html=fs.readFileSync('public-api.html','utf8');
const css=fs.readFileSync('public-api.css','utf8');
execFileSync(process.execPath,['--check','public-api.js']);
for(const id of ['apiDetailDialog','apiDetailClose','detailTitle','detailId','detailProvider','detailCategory','detailSector','detailFormat','detailApproval','detailSummary','detailVerification','detailVerificationNote','detailOfficialLink'])assert.ok(html.includes('id="'+id+'"'),id);
assert.match(html,/aria-modal="true"/);
assert.match(html,/20261011-v19-detail/);
assert.match(js,/function openApiDetail\(id\)/);
assert.match(js,/function closeApiDetail\(\)/);
assert.match(js,/function detailFromUrl\(\)/);
assert.match(js,/verifiedIds\.has\(item.id\)/);
assert.match(js,/detail\.addEventListener\('click'/);
assert.match(js,/detailFromUrl\(\)/);
assert.match(js,/textContent=item.summary/);
assert.match(js,/official.href=item.url/);
assert.match(js,/new URLSearchParams\(window.location.search\)/);
assert.match(css,/\.api-detail-overlay\[hidden\]/);
console.log('V19 detail panel metadata/deep link regression tests passed');
