import assert from 'node:assert/strict';
import {updatePublicApis,pageMatches,matchesOfficial} from './refresh-public-apis.mjs';
const row={id:'15129412',name:'조달청_공공조달통계정보서비스',provider:'조달청',category:'조달·행정',summary:'통계',format:'API',approval:'원문 확인'};
const base={source:'data.go.kr',items:[{...row,id:'15074634',url:'https://www.data.go.kr/data/15074634/openapi.do'}]};
const src={'data/public-apis.json':JSON.stringify(base),'data/public-api-candidates.json':JSON.stringify({items:[row]})};let writes=[];
const read=async name=>src[name],write=async(name,content)=>writes.push({name,content});
const html='<html><body>'+'.'.repeat(220)+' OpenAPI 명 조달청_공공조달통계정보서비스 분류체계 일반공공행정 - 정부자원관리 제공기관 조달청 관리부서명 조달데이터관리팀 설명 공공조달 통계정보를 통합 조회할 수 있는 데이터 서비스입니다. API 유형 REST 데이터 포맷 JSON+XML 운영단계 : 자동승인 </body></html>';
assert.equal(pageMatches(html,row),true);
assert.equal(pageMatches(html.replace(row.name,'다른 데이터'),row),false);
assert.equal(matchesOfficial(row,{...row,provider:'다른기관'}),false);
const fetcher=async()=>({ok:true,headers:new Headers({'content-type':'text/html;charset=utf-8'}),text:async()=>html});
const success=await updatePublicApis({read,write,fetcher});assert.equal(success.added,1);assert.equal(writes.length,1);
const published=JSON.parse(writes[0].content).items;
assert.equal(published.length,2);
assert.equal(published[1].format,'JSON+XML');
assert.equal(published[1].approval,'자동승인');
writes=[];
const rejected=await updatePublicApis({read,write,fetcher:async()=>({ok:false,headers:new Headers(),text:async()=>''})});
assert.equal(rejected.added,0);assert.equal(rejected.failed,1);assert.equal(writes.length,0);
writes=[];
const mismatched=await updatePublicApis({read,write,fetcher:async()=>({ok:true,headers:new Headers({'content-type':'text/html'}),text:async()=>html.replace('제공기관 조달청','제공기관 다른기관')})});
assert.equal(mismatched.added,0);assert.equal(writes.length,0);
console.log('Verified Public API publication safety tests passed');
